# Generated by Django 3.1.2 on 2020-11-04 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 4, 11, 33, 13, 399697)),
        ),
    ]
